### ISSUE TITLE
Is wiping commit history intentional?

### ISSUE THREAD

**Issue by gkze** [mailslurp/mailslurp-client-python#5]
I was trying to update our fork but got a bunch of conflicts

**Comment by jackmahoney** [comment]
Hi sorry for the delay. Our automation process might be causing git history to wipe. Can you share the issues you are finding and how to reproduce? what files conflict for you?

**Comment by jackmahoney** [comment]
I noticed we are potentially overwriting tags, I will do a new release with a fix that will preserve old tags.
